### ISSUE TITLE
Introduce STPA to group and establish contact to STPA authors & experts 

### ISSUE THREAD

**Issue by bulwahn** [elisa-tech/tsc#10]
- [x] Paul to arrange presentation by the STPA expert at CodeThink: Shaun presented STPA in a webinar.
- [ ] If further followed up, create connection between John Thomas from MIT and the ELISA group

From the meeting minutes:

> Open STPA - Sean to give presentation,   Paul to arrange.   What like, what hate. 
> Robin is interested in this.  Handbook has been sent to list.   Sean talking through it.   Learning experience.  Use case that is being done in the open then, can we also support it.  
> AI:  Paul to take lead on this,  and they write a “hello paul” email.   Spin something up with ELISA. 
> Ask John Thomas from MIT -  webinars & training.   Interested in applying further. Paul to connect Kate with them.

**Comment by pahmann** [comment]
This issue is still active as STPA is heavily used in ELISA and we discussed during Architecture WG meetings, that we may try to reach out to STPA authors.
@gabpaoloni @reiterative FYI.

**Comment by pahmann** [comment]
From TSC meeting 2022-11-16:
"Modified STPA" started in Architecture WG and have a tailored STPA for the Kernel. This may lead in a discussion how to handle complex systems with STPA.
Medical devices working with STPA since 3 years and reached out to the authors also few times already.
It is in use for multiple working groups.

When we reach out to STPA responsible we need to have a clear picture. 
There is also an anual STPA event, where we could put together the work from the different working groups and see that we can maybe present something. There is a MIT STPA event, but also a European STAMP meeting.

Paul already talked about it at the European STAMP meeting.

Reach out to STPA beforehand so that they understand our submission in context.

**Comment by pahmann** [comment]
No further action required. We are in contact with STPA people and exchange on demand.
